Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/edit.html]")] with root cause
org.springframework.beans.NotReadablePropertyException: Invalid property 'updateUser' of bean class [com.example.crud_boot_security_proj.entity.Users]: Bean property 'updateUser' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?